name: pool_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0

  
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: PoolFont
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-Light.ttf
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-SemiBold.ttf


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png

