name: pool_app
description: "Pool is a Flutter app for the Brazilian game 'Bolão' (Sweepstake). It allows users to join and manage sweepstakes with friends."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.5.0
  build_runner: ^2.2.0

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: PoolFont
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-Light.ttf
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-SemiBold.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png
